# Generated by Django 3.0.5 on 2020-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_data',
            name='death',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meter_data',
            name='no_patient',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meter_data',
            name='no_recovered',
            field=models.CharField(max_length=10),
        ),
    ]
