# Generated by Django 3.0.5 on 2020-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200405_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_data',
            name='country_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='meter_data',
            name='death',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='meter_data',
            name='no_patient',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='meter_data',
            name='no_recovered',
            field=models.CharField(default='', max_length=10),
        ),
    ]
