# Generated by Django 3.0.5 on 2020-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200405_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpline_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(default='', max_length=10)),
                ('Helpline_no', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
