# Generated by Django 3.0.5 on 2020-04-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_helpline_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_data',
            name='s_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpline_data',
            name='Helpline_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='helpline_data',
            name='State_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
