# Generated by Django 3.0.5 on 2020-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200406_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default='', max_length=20)),
                ('Phone_no', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('Zip', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Donation', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
