# Generated by Django 3.0.5 on 2020-04-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_donation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('newsdata', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='donation_data',
            name='Donation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
