# Generated by Django 3.0.5 on 2020-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200408_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpline_data',
            name='s_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
